---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  serviceName: {{ .Chart.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.app.image }}
          env:
            {{- range $key, $value := .Values.app.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          ports:
            - name: "api"
              containerPort: 7777
              protocol: TCP
            - name: "game"
              containerPort: 7777
              protocol: UDP
            - name: "messaging"
              containerPort: 8888
              protocol: TCP
          startupProbe:
            exec:
              command:
                - "/bin/sh"
                - "-c"
                - "/home/steam/healthcheck.sh"
            failureThreshold: 100
            periodSeconds: 2
          livenessProbe:
            exec:
              command:
                - "/bin/sh"
                - "-c"
                - "/home/steam/healthcheck.sh"
            periodSeconds: 30
          volumeMounts:
            - name: {{ .Chart.Name }}-config
              mountPath: /config
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
  volumeClaimTemplates:
    - metadata:
        name: {{ .Chart.Name }}-config
        annotations:
          "helm.sh/resource-policy": keep
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path
        resources:
          requests:
            storage: 20Gi
